module.exports = {
    NAVIGATION: 'NAVIGATION',
    TODO_CREATED: 'TODO_CREATED',
    TODO_DELETED: 'TODO_DELETED',
    TODO_UPDATED: 'TODO_UPDATED',
    REGISTER: 'REGISTER',
    LOGIN: 'LOGIN',
    TOKEN_REFRESH: 'TOKEN_REFRESH',
    GENERIC: 'GENERIC'
}